-- ============================================================================
--  ตาราง Schools — เก็บข้อมูลโรงเรียนแทนการพิมพ์ฝังไว้ในโค้ด
--
--  วิธีรัน: Supabase Dashboard > SQL Editor > วางทั้งไฟล์ > Run
--  รันซ้ำได้ ไม่พัง (ใช้ if not exists และเช็กก่อนเพิ่มแถว)
--
--  เดิมชื่อโรงเรียนถูกพิมพ์ฝังไว้ในโค้ด 18 จุด และสะกดไม่ตรงกันด้วย
--  ย้ายมาไว้ที่นี่เพื่อให้แก้ที่เดียวจบ และรองรับหลายโรงเรียนในอนาคต
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 1) สร้างตาราง
--
--    คอลัมน์ที่ใบลาใช้จริงตอนนี้: fullName, namePart1, namePart2, address,
--    affiliation  ส่วน localCode/province/district/subdistrict เตรียมไว้ให้
--    ตอนทำหลายโรงเรียน (ยังไม่มีโค้ดอ่าน ใส่ไว้ก่อนจะได้ไม่ต้องแก้ตารางซ้ำ)
-- ----------------------------------------------------------------------------

create table if not exists public."Schools" (
  id_school     bigint generated by default as identity primary key,

  -- ชื่อเต็มที่ใช้ในหัวเอกสารราชการ
  "fullName"    text not null,

  -- ชื่อที่ตัดเป็นสองท่อน ใช้ตอนที่ใบลาต้องขึ้นบรรทัดใหม่กลางชื่อ
  "namePart1"   text,
  "namePart2"   text,

  address       text,
  affiliation   text,

  -- เตรียมไว้สำหรับระบบหลายโรงเรียน
  "localCode"   text,
  province      text,
  district      text,
  subdistrict   text,

  "createdAt"   timestamptz default now(),
  "updatedAt"   timestamptz default now()
);

comment on table public."Schools" is
  'ข้อมูลโรงเรียน ใช้แทนชื่อที่เคยพิมพ์ฝังไว้ในโค้ด';


-- ----------------------------------------------------------------------------
-- 2) ใส่ข้อมูลโรงเรียนปัจจุบัน (เฉพาะตอนที่ยังไม่มีแถวใด ๆ)
-- ----------------------------------------------------------------------------

insert into public."Schools"
  ("fullName", "namePart1", "namePart2", address, affiliation,
   province, district)
select
  'โรงเรียนรมย์บุรีพิทยาคม รัชมังคลาภิเษก',
  'โรงเรียนรมย์บุรีพิทยาคม',
  'รัชมังคลาภิเษก',
  'อำเภอบ้านด่าน จังหวัดบุรีรัมย์ 31000',
  'สังกัดสำนักงานเขตพื้นที่การศึกษามัธยมศึกษาบุรีรัมย์ กระทรวงศึกษาธิการ',
  'บุรีรัมย์',
  'บ้านด่าน'
where not exists (select 1 from public."Schools");


-- ----------------------------------------------------------------------------
-- 3) เปิด RLS + policy
--
--    ทุกคนที่ล็อกอินแล้วอ่านได้ เพราะใบลาทุกใบต้องใช้ชื่อโรงเรียน
--    แก้ไขได้เฉพาะผู้ดูแลระบบ ใช้ฟังก์ชัน is_admin() ชุดเดียวกับตารางอื่น
--    (สร้างไว้แล้วตอนรัน enable_rls.sql)
--
--    ⚠️ ห้ามลืมขั้นนี้ ไม่งั้นใครก็แก้ชื่อโรงเรียนในใบลาราชการได้
-- ----------------------------------------------------------------------------

alter table public."Schools" enable row level security;

-- ล้าง policy เดิมก่อน เผื่อรันไฟล์นี้ซ้ำ
do $$
declare
  p record;
begin
  for p in
    select policyname from pg_policies
    where schemaname = 'public' and tablename = 'Schools'
  loop
    execute format('drop policy %I on public."Schools"', p.policyname);
  end loop;
end $$;

create policy schools_select on public."Schools"
  for select to authenticated using (true);

create policy schools_write on public."Schools"
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());


-- ----------------------------------------------------------------------------
-- 4) ตรวจผล — ต้องได้ 1 แถว, rowsecurity = true, policies = 2
-- ----------------------------------------------------------------------------

select
  (select count(*) from public."Schools")            as จำนวนแถว,
  (select "fullName" from public."Schools"
    order by id_school limit 1)                      as ชื่อโรงเรียน,
  (select rowsecurity from pg_tables
    where schemaname = 'public' and tablename = 'Schools') as เปิด_rls,
  (select count(*) from pg_policies
    where schemaname = 'public' and tablename = 'Schools') as จำนวน_policy;
