-- ============================================================================
--  แม่แบบฟอร์ม (ใบลา / ใบขออนุญาตไปราชการ) — ตั้งค่าจาก web
--
--  วิธีรัน: Supabase Dashboard > SQL Editor > วางทั้งไฟล์ > Run
--  รันซ้ำได้ ไม่พัง (แม่แบบที่บันทึกไว้แล้วไม่หาย)
--  ต้องรันก่อนแล้ว: enable_rls.sql, multi_school_step3_rls.sql, super_admin.sql
--
--  หลักการ:
--    - 1 แถว = 1 เวอร์ชัน ไม่แก้ทับ — บันทึกใหม่ = เพิ่มแถวใหม่ (เลขเวอร์ชัน +1)
--      ย้อนกลับ = บันทึกเวอร์ชันเก่าซ้ำเป็นเวอร์ชันใหม่ ประวัติจึงครบเสมอ
--    - id_school ว่าง = แม่แบบกลาง (ใช้ทุกโรงเรียนที่ไม่มีแม่แบบของตัวเอง)
--      id_school มีค่า = แม่แบบเฉพาะโรงเรียนนั้น
--    - uses_default = true คือโรงเรียนนั้น "กลับไปใช้แม่แบบกลาง" (template ว่าง)
--    - แม่แบบที่ใช้จริง: เวอร์ชันล่าสุดของโรงเรียน ถ้าไม่มีหรือเป็น uses_default
--      ใช้เวอร์ชันล่าสุดของแม่แบบกลาง (ฟังก์ชัน current_form_template)
--      ถ้ายังไม่มีแม่แบบกลางในฐานข้อมูล app/web ใช้ค่าเริ่มต้นในโค้ด
--
--  สิทธิ์: ทุกคนที่ล็อกอินอ่านแม่แบบกลาง + ของโรงเรียนตัวเองได้ (app ต้องใช้วาดฟอร์ม)
--          บันทึก / ลบ ได้เฉพาะผู้ดูแลส่วนกลาง (ตั้งจาก web)
--
--  ย้อนกลับ: drop table if exists public."FormTemplates";
-- ============================================================================


create table if not exists public."FormTemplates" (
  id_template   bigint generated by default as identity primary key,
  form_type     text   not null,
  id_school     bigint references public."Schools"(id_school) on delete cascade,
  version       int    not null,
  template      jsonb,
  uses_default  boolean not null default false,
  note          text,
  created_by    bigint references public."Teachers"(id_user) on delete set null,
  "createdAt"   timestamptz not null default now(),

  constraint form_templates_type_ok
    check (form_type in ('leave', 'trip')),
  constraint form_templates_content_ok
    check (uses_default = (template is null)),
  constraint form_templates_default_needs_school
    check (not (uses_default and id_school is null)),
  constraint form_templates_version_unique
    unique nulls not distinct (form_type, id_school, version)
);

create index if not exists "FormTemplates_lookup_idx"
  on public."FormTemplates" (form_type, id_school, version desc);


-- ----------------------------------------------------------------------------
-- trigger: เลขเวอร์ชัน + ผู้บันทึก (ไม่เชื่อค่าจาก web)
-- ----------------------------------------------------------------------------

create or replace function public.fill_form_template()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  -- กันบันทึกพร้อมกันสองคนได้เลขซ้ำ
  perform pg_advisory_xact_lock(hashtext('FormTemplates:' || new.form_type || ':' || coalesce(new.id_school::text, '-')));
  select coalesce(max(version), 0) + 1 into new.version
  from "FormTemplates"
  where form_type = new.form_type and id_school is not distinct from new.id_school;
  if auth.uid() is not null then
    new.created_by := public.current_teacher_id();
  end if;
  return new;
end;
$$;

drop trigger if exists fill_form_template on public."FormTemplates";
create trigger fill_form_template
  before insert on public."FormTemplates"
  for each row execute function public.fill_form_template();


-- ----------------------------------------------------------------------------
-- แม่แบบที่ใช้จริงของโรงเรียนหนึ่ง (app เรียกตอนวาดฟอร์ม)
-- คืน 0 แถว = ยังไม่มีแม่แบบในฐานข้อมูล → ใช้ค่าเริ่มต้นในโค้ด
-- ----------------------------------------------------------------------------

create or replace function public.current_form_template(p_form_type text, p_school bigint)
returns table (id_template bigint, id_school bigint, version int, template jsonb)
language sql stable
as $$
  with own as (
    select t.id_template, t.id_school, t.version, t.template, t.uses_default
    from "FormTemplates" t
    where t.form_type = p_form_type and t.id_school = p_school
    order by t.version desc
    limit 1
  ),
  global as (
    select t.id_template, t.id_school, t.version, t.template
    from "FormTemplates" t
    where t.form_type = p_form_type and t.id_school is null
    order by t.version desc
    limit 1
  )
  select o.id_template, o.id_school, o.version, o.template from own o where not o.uses_default
  union all
  select g.id_template, g.id_school, g.version, g.template from global g
  where not exists (select 1 from own o where not o.uses_default);
$$;

grant execute on function public.current_form_template(text, bigint) to authenticated;


-- ----------------------------------------------------------------------------
-- RLS
-- ----------------------------------------------------------------------------

alter table public."FormTemplates" enable row level security;

do $$
declare
  p record;
begin
  for p in select policyname from pg_policies
           where schemaname = 'public' and tablename = 'FormTemplates'
  loop
    execute format('drop policy %I on public."FormTemplates"', p.policyname);
  end loop;
end $$;

create policy form_templates_select on "FormTemplates"
  for select to authenticated
  using (id_school is null or public.can_see_school(id_school));

create policy form_templates_insert on "FormTemplates"
  for insert to authenticated
  with check (public.is_super_admin());

create policy form_templates_delete on "FormTemplates"
  for delete to authenticated
  using (public.is_super_admin());

-- ไม่มี policy update — เวอร์ชันที่บันทึกแล้วแก้ไม่ได้


notify pgrst, 'reload schema';


-- ----------------------------------------------------------------------------
-- ตรวจผล — rowsecurity = true / policies = 3 / trigger = 1 / ฟังก์ชัน = 1
-- ----------------------------------------------------------------------------

select (select rowsecurity from pg_tables
         where schemaname = 'public' and tablename = 'FormTemplates')          as rowsecurity,
       (select count(*) from pg_policies
         where schemaname = 'public' and tablename = 'FormTemplates')          as policies,
       (select count(*) from pg_trigger
         where tgname = 'fill_form_template' and not tgisinternal)             as trigger,
       (select count(*) from pg_proc where proname = 'current_form_template')  as ฟังก์ชัน,
       (select count(*) from public."FormTemplates")                           as แม่แบบที่บันทึกไว้;
