-- ============================================================================
--  แจ้งเตือนใน app — ผู้ดูแลระบบได้รับแจ้งเมื่อมีใบลาใหม่
--
--  วิธีรัน: Supabase Dashboard > SQL Editor > วางทั้งไฟล์ > Run
--  รันซ้ำได้ ไม่พัง (แจ้งเตือนที่มีอยู่แล้วไม่หาย)
--  ต้องรันก่อนแล้ว: enable_rls.sql, multi_school_step1_id_school.sql,
--                  multi_school_step3_rls.sql, admin_role_by_id.sql,
--                  leaves_firebase_id.sql
--
--  หลักการ:
--    - ฐานข้อมูลสร้างแจ้งเตือนเอง (trigger บน Leaves) — ไม่ว่าใบลาจะมาจาก
--      app บนคอมพิวเตอร์ มือถือ หรือแอดมินส่งแทน ก็แจ้งเหมือนกัน
--      และครูปลอมแจ้งเตือนส่งให้แอดมินไม่ได้ (ไม่มี policy insert)
--    - 1 แถวต่อผู้รับ 1 คน — แต่ละแอดมินอ่าน/ลบของตัวเองได้อิสระ
--    - ผู้รับ = ผู้ดูแลระบบ (id_role = 22) ของโรงเรียนเจ้าของใบลา
--      ไม่แจ้งคนที่เป็นเจ้าของใบลาเอง และไม่แจ้งคนที่กดส่งเอง
--    - ใบลาที่นำเข้าจาก Firebase (firebase_id มีค่า) ไม่แจ้ง — กันแจ้งเตือน
--      ท่วมตอนนำเข้าข้อมูลเก่า
--
--  ย้อนกลับ:
--    drop trigger if exists notify_new_leave on public."Leaves";
--    drop table if exists public."AppNotifications";
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 1) ตาราง
-- ----------------------------------------------------------------------------

create table if not exists public."AppNotifications" (
  id_notification  bigint generated by default as identity primary key,
  id_school        bigint references public."Schools"(id_school) on delete cascade,
  recipient_id     bigint not null references public."Teachers"(id_user) on delete cascade,
  type             text   not null,      -- leave_new (เผื่ออนาคต: trip_new ฯลฯ)
  title            text   not null,
  body             text,
  ref_table        text,                  -- ตารางต้นทาง เช่น Leaves
  ref_id           bigint,                -- PK ของแถวต้นทาง
  actor_id         bigint references public."Teachers"(id_user) on delete set null,
  read_at          timestamptz,
  "createdAt"      timestamptz not null default now()
);

create index if not exists "AppNotifications_recipient_idx"
  on public."AppNotifications" (recipient_id, "createdAt" desc);
create index if not exists "AppNotifications_unread_idx"
  on public."AppNotifications" (recipient_id)
  where read_at is null;


-- ----------------------------------------------------------------------------
-- 2) trigger: ใบลาใหม่ → แจ้งผู้ดูแลระบบของโรงเรียนนั้น
--
--    ข้อความประกอบจากฐานข้อมูล (ชื่อครู / ประเภทลา / วันที่) ไม่รับจาก app
--    ใช้ to_jsonb อ่านคอลัมน์ เผื่อบางคอลัมน์ไม่มีในตาราง
--    ถ้าสร้างแจ้งเตือนไม่สำเร็จ ใบลายังบันทึกได้ตามปกติ (ไม่ให้แจ้งเตือนทำใบลาพัง)
-- ----------------------------------------------------------------------------

create or replace function public.thai_short_date(d date)
returns text
language sql immutable
as $$
  select extract(day from d)::int || ' '
      || (array['ม.ค.','ก.พ.','มี.ค.','เม.ย.','พ.ค.','มิ.ย.',
                'ก.ค.','ส.ค.','ก.ย.','ต.ค.','พ.ย.','ธ.ค.'])[extract(month from d)::int]
      || ' ' || (extract(year from d)::int + 543);
$$;

create or replace function public.notify_new_leave()
returns trigger
language plpgsql security definer set search_path = public
as $$
declare
  leave     jsonb := to_jsonb(new);
  owner     record;
  type_name text;
  start_d   date;
  end_d     date;
  days      text;
  when_text text;
  actor     bigint := public.current_teacher_id();
begin
  if leave ->> 'firebase_id' is not null then
    return new;
  end if;

  select id_user, id_school, coalesce(to_jsonb(t) ->> 'fullName', to_jsonb(t) ->> 'fullname', '-') as name
    into owner
  from "Teachers" t where t.id_user = new.id_user;
  if not found then
    return new;
  end if;

  select coalesce(to_jsonb(lt) ->> 'leaveName', to_jsonb(lt) ->> 'Value')
    into type_name
  from "LeaveTypes" lt
  where (to_jsonb(lt) ->> 'id_leaveType') = leave ->> 'id_leaveType'
  limit 1;

  start_d := nullif(leave ->> 'startDate', '')::date;
  end_d   := coalesce(nullif(leave ->> 'endDate', '')::date, start_d);
  days    := nullif(leave ->> 'totalDays', '');
  when_text := case
    when start_d is null then ''
    when end_d = start_d then public.thai_short_date(start_d)
    else public.thai_short_date(start_d) || ' – ' || public.thai_short_date(end_d)
  end;

  insert into "AppNotifications"
    (id_school, recipient_id, type, title, body, ref_table, ref_id, actor_id)
  select owner.id_school,
         a.id_user,
         'leave_new',
         owner.name || ' ยื่น' || coalesce(type_name, 'ใบลา'),
         concat_ws(' · ',
           nullif(when_text, ''),
           case when days is not null
                then trim_scale(days::numeric)::text || ' วัน' end,
           nullif(leave ->> 'reason', '')),
         'Leaves',
         (leave ->> 'id_leaves')::bigint,
         actor
  from "Teachers" a
  where a.id_school = owner.id_school
    and a.id_role = 22
    and a.id_user <> owner.id_user
    and a.id_user is distinct from actor;

  return new;
exception when others then
  raise warning 'notify_new_leave: %', sqlerrm;
  return new;
end;
$$;

drop trigger if exists notify_new_leave on public."Leaves";
create trigger notify_new_leave
  after insert on public."Leaves"
  for each row execute function public.notify_new_leave();


-- ----------------------------------------------------------------------------
-- 3) กันแก้ช่องอื่นนอกจาก "อ่านแล้ว"
-- ----------------------------------------------------------------------------

create or replace function public.guard_notification_update()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  if (to_jsonb(new) - 'read_at') is distinct from (to_jsonb(old) - 'read_at') then
    raise exception 'แก้ได้เฉพาะสถานะอ่านแล้ว';
  end if;
  return new;
end;
$$;

drop trigger if exists guard_notification_update on public."AppNotifications";
create trigger guard_notification_update
  before update on public."AppNotifications"
  for each row execute function public.guard_notification_update();


-- ----------------------------------------------------------------------------
-- 4) RLS — เห็น / อ่าน / ลบ ได้เฉพาะแจ้งเตือนของตัวเอง ไม่มีใครสร้างเองได้
-- ----------------------------------------------------------------------------

alter table public."AppNotifications" enable row level security;

do $$
declare
  p record;
begin
  for p in select policyname from pg_policies
           where schemaname = 'public' and tablename = 'AppNotifications'
  loop
    execute format('drop policy %I on public."AppNotifications"', p.policyname);
  end loop;
end $$;

create policy notifications_select on "AppNotifications"
  for select to authenticated
  using (recipient_id = public.current_teacher_id());

create policy notifications_update on "AppNotifications"
  for update to authenticated
  using (recipient_id = public.current_teacher_id())
  with check (recipient_id = public.current_teacher_id());

create policy notifications_delete on "AppNotifications"
  for delete to authenticated
  using (recipient_id = public.current_teacher_id());


-- ----------------------------------------------------------------------------
-- 5) Realtime — ให้ app เห็นแจ้งเตือนใหม่ทันทีโดยไม่ต้องรีเฟรช
--    (Realtime ส่งเฉพาะแถวที่ RLS อนุญาตให้ผู้ใช้คนนั้นเห็น)
-- ----------------------------------------------------------------------------

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1 from pg_publication_tables
       where pubname = 'supabase_realtime'
         and schemaname = 'public' and tablename = 'AppNotifications') then
    alter publication supabase_realtime add table public."AppNotifications";
  end if;
end $$;


notify pgrst, 'reload schema';


-- ----------------------------------------------------------------------------
-- 6) ตรวจผล
--    rowsecurity = true / policies = 3 / trigger บน Leaves = 1 / realtime = true
--    ผู้รับ = รายชื่อผู้ดูแลระบบที่จะได้รับแจ้งเตือน แยกโรงเรียน
-- ----------------------------------------------------------------------------

select (select rowsecurity from pg_tables
         where schemaname = 'public' and tablename = 'AppNotifications')          as rowsecurity,
       (select count(*) from pg_policies
         where schemaname = 'public' and tablename = 'AppNotifications')          as policies,
       (select count(*) from pg_trigger
         where tgname = 'notify_new_leave' and not tgisinternal)                  as trigger_ใบลา,
       exists (select 1 from pg_publication_tables
                where pubname = 'supabase_realtime' and tablename = 'AppNotifications') as realtime,
       (select string_agg(id_school || ': ' || n || ' คน', ', ' order by id_school)
          from (select id_school, count(*) n from public."Teachers"
                where id_role = 22 group by id_school) x)                         as ผู้รับ;
