-- ============================================================================
--  ประชุมราชการ / ไปราชการ — พาร์ท 1: ตาราง + RLS
--
--  วิธีรัน: Supabase Dashboard > SQL Editor > วางทั้งไฟล์ > Run
--  รันซ้ำได้ ไม่พัง (ข้อมูลที่บันทึกไว้แล้วไม่หาย)
--  ต้องรันก่อนแล้ว: enable_rls.sql, multi_school_step1_id_school.sql,
--                  multi_school_step3_rls.sql, admin_role_by_id.sql
--
--  รอบนี้ "ยังไม่เปลี่ยนการทำงานของแอป" — แค่สร้างตารางรอไว้
--  (พาร์ท 2 สิทธิ์, พาร์ท 3 หน้าจอ)
--
--  แนวคิด:
--    OfficialTrips        1 แถว = ไปราชการ 1 เรื่อง (ประชุม/อบรม/สัมมนา)
--                         id_user = ผู้บันทึกคำขอ (หัวหน้าคณะ)
--    OfficialTripMembers  รายชื่อทุกคนที่ไป รวมผู้บันทึกเอง (เพิ่มให้อัตโนมัติ)
--                         ใช้ตอบคำถาม "วันนี้ใครไปราชการ" และนับลงรายงาน
--
--  ไปราชการ "ไม่นับเป็นวันลา" — แยกตารางจาก Leaves โดยตั้งใจ
--
--  สิทธิ์ (เหมือนใบลา):
--    ครู/ผู้บริหาร   เห็นของทั้งโรงเรียน, บันทึก/แก้/ลบของตัวเองได้เฉพาะ
--                   ที่ยังรอพิจารณา, อนุมัติเองไม่ได้
--                   หลังอนุมัติแล้ว แก้ได้เฉพาะช่องรายงานผล + ไฟล์แนบ
--    ผู้ดูแลระบบ (22) ทำได้ทุกอย่างในโรงเรียนตัวเอง
--    ผู้ดูแลส่วนกลาง ทำได้ทุกโรงเรียน
--
--  ย้อนกลับ (ลบทิ้งทั้งหมด รวมข้อมูล):
--    drop table if exists public."OfficialTripMembers", public."OfficialTrips";
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 0) ฟังก์ชันผู้ช่วย: โรงเรียนของครูคนหนึ่ง
--    (นิยามเดียวกับใน fine_permissions.sql — ใส่ซ้ำไว้ให้ไฟล์นี้รันได้เอง)
-- ----------------------------------------------------------------------------

create or replace function public.teacher_school(target bigint)
returns bigint
language sql stable security definer set search_path = public
as $$
  select id_school from "Teachers" where id_user = target;
$$;
grant execute on function public.teacher_school(bigint) to authenticated;


-- ----------------------------------------------------------------------------
-- 1) ตาราง OfficialTrips
--
--    วันที่ใช้ชนิด date จริง (ไม่ใช่ข้อความวันที่ไทยแบบ Leaves)
--    totalDays แอปคำนวณส่งมา (หักวันหยุดแบบเดียวกับใบลา)
--    ช่องไฟล์แนบ / รายงานผล เตรียมไว้ให้พาร์ท 7 — ว่างได้
-- ----------------------------------------------------------------------------

create table if not exists public."OfficialTrips" (
  id_trip          bigint generated by default as identity primary key,
  id_school        bigint references public."Schools"(id_school),
  id_user          bigint not null references public."Teachers"(id_user) on delete cascade,

  -- เรื่องที่ไป
  title            text not null,                 -- เรื่อง เช่น ประชุมผู้บริหาร สพม.
  "tripType"       text not null default 'ประชุม', -- ประชุม / อบรม / สัมมนา / อื่นๆ
  organizer        text,                          -- หน่วยงานที่จัด
  location         text,                          -- สถานที่
  province         text,

  -- หนังสืออ้างอิง
  "docNumber"      text,                          -- เลขที่หนังสือเชิญ/คำสั่ง
  "docDate"        date,

  -- วันเวลา
  "startDate"      date not null,
  "endDate"        date not null,
  "isHalfDay"      boolean not null default false,
  "halfDayPeriod"  text,                          -- morning / afternoon
  "totalDays"      numeric(6, 2),

  -- การเดินทาง / ค่าใช้จ่าย
  "travelMode"     text,                          -- รถส่วนตัว / รถราชการ / รถโดยสาร ฯลฯ
  "budgetSource"   text,                          -- เบิกต้นสังกัด / ผู้จัดออกให้ / ไม่เบิก
  "estimatedCost"  numeric(12, 2),

  -- การอนุมัติ
  status           text not null default 'รอพิจารณา',
  "approvedBy"     bigint references public."Teachers"(id_user) on delete set null,
  "approvedAt"     timestamptz,
  "approverNote"   text,

  -- หลังกลับจากราชการ (พาร์ท 7)
  "attachmentUrl"  text,
  "reportSummary"  text,
  "reportedAt"     timestamptz,

  note             text,
  "createdAt"      timestamptz not null default now(),
  "updatedAt"      timestamptz not null default now(),

  constraint official_trips_dates_ok
    check ("endDate" >= "startDate"),
  constraint official_trips_status_ok
    check (status in ('รอพิจารณา', 'อนุมัติ', 'ไม่อนุมัติ', 'ยกเลิก')),
  constraint official_trips_half_day_ok
    check (not "isHalfDay"
           or ("startDate" = "endDate"
               and "halfDayPeriod" in ('morning', 'afternoon')))
);

create index if not exists "OfficialTrips_school_date_idx"
  on public."OfficialTrips" (id_school, "startDate");
create index if not exists "OfficialTrips_id_user_idx"
  on public."OfficialTrips" (id_user);


-- ----------------------------------------------------------------------------
-- 2) ตาราง OfficialTripMembers — ทุกคนที่ไป
-- ----------------------------------------------------------------------------

create table if not exists public."OfficialTripMembers" (
  id_trip      bigint not null references public."OfficialTrips"(id_trip) on delete cascade,
  id_user      bigint not null references public."Teachers"(id_user) on delete cascade,
  "createdAt"  timestamptz not null default now(),
  primary key (id_trip, id_user)
);

create index if not exists "OfficialTripMembers_id_user_idx"
  on public."OfficialTripMembers" (id_user);


-- ----------------------------------------------------------------------------
-- 3) trigger: id_school + updatedAt ของ OfficialTrips
--
--    id_school ใช้โรงเรียนของผู้บันทึก "เสมอ" ไม่เชื่อค่าจากแอป
--    (เหมือน Leaves — กันการบันทึกไปโผล่ในโรงเรียนอื่น)
-- ----------------------------------------------------------------------------

create or replace function public.fill_official_trip()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  new.id_school := coalesce(public.teacher_school(new.id_user), new.id_school);
  new."updatedAt" := now();
  return new;
end;
$$;

drop trigger if exists fill_official_trip on public."OfficialTrips";
create trigger fill_official_trip
  before insert or update on public."OfficialTrips"
  for each row execute function public.fill_official_trip();


-- ----------------------------------------------------------------------------
-- 4) trigger: กันอนุมัติเอง (เหมือน guard_leave_approval ของใบลา)
--
--    คนที่ไม่ใช่ผู้ดูแลระบบ:
--      บันทึกใหม่ได้เฉพาะสถานะรอพิจารณา และห้ามใส่ข้อมูลผู้อนุมัติ
--      ที่ยังรอพิจารณา: แก้ได้ทุกช่อง ยกเว้นสถานะ/ผู้อนุมัติ, ลบได้
--      ที่ดำเนินการแล้ว: แก้ได้เฉพาะรายงานผล + ไฟล์แนบ, ลบไม่ได้
-- ----------------------------------------------------------------------------

create or replace function public.guard_official_trip()
returns trigger
language plpgsql security definer set search_path = public
as $$
declare
  approval_cols constant text[] :=
    array['status', 'approvedBy', 'approvedAt', 'approverNote'];
  report_cols constant text[] :=
    array['attachmentUrl', 'reportSummary', 'reportedAt', 'updatedAt'];
  col text;
begin
  if auth.uid() is null or public.is_admin() then
    return coalesce(new, old);
  end if;

  if tg_op = 'INSERT' then
    if new.status <> 'รอพิจารณา'
       or new."approvedBy" is not null
       or new."approvedAt" is not null then
      raise exception 'อนุมัติการไปราชการได้เฉพาะผู้ดูแลระบบ';
    end if;
    return new;
  end if;

  if tg_op = 'DELETE' then
    if old.status <> 'รอพิจารณา' then
      raise exception 'รายการที่ดำเนินการแล้ว ลบได้เฉพาะผู้ดูแลระบบ';
    end if;
    return old;
  end if;

  -- UPDATE
  foreach col in array approval_cols loop
    if (to_jsonb(new) -> col) is distinct from (to_jsonb(old) -> col) then
      raise exception 'อนุมัติหรือเปลี่ยนสถานะได้เฉพาะผู้ดูแลระบบ';
    end if;
  end loop;

  if old.status <> 'รอพิจารณา' then
    -- เทียบทั้งแถวโดยตัดช่องรายงานผลออก ถ้ายังต่างกัน = แก้ช่องอื่น
    if (to_jsonb(new) - report_cols) is distinct from (to_jsonb(old) - report_cols) then
      raise exception 'รายการที่ดำเนินการแล้ว แก้ได้เฉพาะรายงานผลและไฟล์แนบ';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists guard_official_trip on public."OfficialTrips";
create trigger guard_official_trip
  before insert or update or delete on public."OfficialTrips"
  for each row execute function public.guard_official_trip();


-- ----------------------------------------------------------------------------
-- 5) trigger: เพิ่มผู้บันทึกเป็นผู้ร่วมเดินทางอัตโนมัติ
-- ----------------------------------------------------------------------------

create or replace function public.add_trip_owner_member()
returns trigger
language plpgsql security definer set search_path = public
as $$
begin
  insert into "OfficialTripMembers"(id_trip, id_user)
  values (new.id_trip, new.id_user)
  on conflict do nothing;
  return new;
end;
$$;

drop trigger if exists add_trip_owner_member on public."OfficialTrips";
create trigger add_trip_owner_member
  after insert on public."OfficialTrips"
  for each row execute function public.add_trip_owner_member();


-- ----------------------------------------------------------------------------
-- 6) trigger: ผู้ร่วมเดินทาง
--    - ต้องเป็นครูโรงเรียนเดียวกับรายการ
--    - รายการที่ดำเนินการแล้ว เปลี่ยนรายชื่อได้เฉพาะผู้ดูแลระบบ
--      (ลบทั้งรายการโดยแอดมิน → cascade ลบรายชื่อได้ตามปกติ)
-- ----------------------------------------------------------------------------

create or replace function public.guard_trip_member()
returns trigger
language plpgsql security definer set search_path = public
as $$
declare
  trip record;
  row_trip bigint := coalesce(new.id_trip, old.id_trip);
begin
  select id_school, status into trip
  from "OfficialTrips" where id_trip = row_trip;

  -- cascade จากการลบรายการ (แถวแม่หายไปแล้ว)
  if not found then
    return coalesce(new, old);
  end if;

  if tg_op in ('INSERT', 'UPDATE')
     and public.teacher_school(new.id_user) is distinct from trip.id_school then
    raise exception 'ผู้ร่วมเดินทางต้องเป็นบุคลากรโรงเรียนเดียวกัน';
  end if;

  if auth.uid() is not null
     and not public.is_admin()
     and trip.status <> 'รอพิจารณา' then
    raise exception 'รายการที่ดำเนินการแล้ว เปลี่ยนรายชื่อได้เฉพาะผู้ดูแลระบบ';
  end if;

  return coalesce(new, old);
end;
$$;

drop trigger if exists guard_trip_member on public."OfficialTripMembers";
create trigger guard_trip_member
  before insert or update or delete on public."OfficialTripMembers"
  for each row execute function public.guard_trip_member();


-- ----------------------------------------------------------------------------
-- 7) RLS
-- ----------------------------------------------------------------------------

alter table public."OfficialTrips"       enable row level security;
alter table public."OfficialTripMembers" enable row level security;

do $$
declare
  t text;
  p record;
begin
  foreach t in array array['OfficialTrips', 'OfficialTripMembers']
  loop
    for p in select policyname from pg_policies
             where schemaname = 'public' and tablename = t
    loop
      execute format('drop policy %I on public.%I', p.policyname, t);
    end loop;
  end loop;
end $$;

-- OfficialTrips — เหมือน Leaves
create policy official_trips_select on "OfficialTrips"
  for select to authenticated
  using (public.can_see_school(id_school));

create policy official_trips_insert on "OfficialTrips"
  for insert to authenticated
  with check (public.can_see_school(public.teacher_school(id_user))
              and (id_user = public.current_teacher_id() or public.is_approver()));

create policy official_trips_update on "OfficialTrips"
  for update to authenticated
  using (public.can_see_school(id_school)
         and (id_user = public.current_teacher_id() or public.is_approver()))
  with check (public.can_see_school(id_school)
              and (id_user = public.current_teacher_id() or public.is_approver()));

create policy official_trips_delete on "OfficialTrips"
  for delete to authenticated
  using (public.can_see_school(id_school)
         and (id_user = public.current_teacher_id() or public.is_approver()));

-- OfficialTripMembers — เห็นได้ถ้าเห็นรายการ / แก้ได้ถ้าเป็นเจ้าของรายการหรือแอดมิน
create policy trip_members_select on "OfficialTripMembers"
  for select to authenticated
  using (exists (select 1 from "OfficialTrips" t
                 where t.id_trip = "OfficialTripMembers".id_trip
                   and public.can_see_school(t.id_school)));

create policy trip_members_write on "OfficialTripMembers"
  for all to authenticated
  using (exists (select 1 from "OfficialTrips" t
                 where t.id_trip = "OfficialTripMembers".id_trip
                   and public.can_see_school(t.id_school)
                   and (t.id_user = public.current_teacher_id()
                        or public.is_approver())))
  with check (exists (select 1 from "OfficialTrips" t
                      where t.id_trip = "OfficialTripMembers".id_trip
                        and public.can_see_school(t.id_school)
                        and (t.id_user = public.current_teacher_id()
                             or public.is_approver())));


-- ให้ PostgREST รีโหลด schema เพื่อให้แอปมองเห็นตารางใหม่ทันที
notify pgrst, 'reload schema';


-- ----------------------------------------------------------------------------
-- 8) ตรวจผล
--    ทั้งสองตารางต้อง rowsecurity = true
--    policy: OfficialTrips 4 / OfficialTripMembers 2
--    trigger: OfficialTrips 3 / OfficialTripMembers 1
-- ----------------------------------------------------------------------------

select c.tablename,
       c.rowsecurity,
       (select count(*) from pg_policies p
         where p.schemaname = 'public' and p.tablename = c.tablename) as policies,
       (select count(*) from pg_trigger g
         where g.tgrelid = format('public.%I', c.tablename)::regclass
           and not g.tgisinternal)                                      as triggers
from pg_tables c
where c.schemaname = 'public'
  and c.tablename in ('OfficialTrips', 'OfficialTripMembers')
order by c.tablename;
