// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfTTxNt5EXXPk0w15YlH-EH4c_0sFkLjo',
    appId: '1:441174887983:web:953d6e29407d3a0d3d00da',
    messagingSenderId: '441174887983',
    projectId: 'rbp-chanikarnn',
    authDomain: 'rbp-chanikarnn.firebaseapp.com',
    storageBucket: 'rbp-chanikarnn.firebasestorage.app',
    measurementId: 'G-902BBPMWC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfTTxNt5EXXPk0w15YlH-EH4c_0sFkLjo',
    appId: '1:441174887983:android:0000000000000000000000', // Mock Android (Project only uses Web)
    messagingSenderId: '441174887983',
    projectId: 'rbp-chanikarnn',
    storageBucket: 'rbp-chanikarnn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfTTxNt5EXXPk0w15YlH-EH4c_0sFkLjo',
    appId: '1:441174887983:ios:0000000000000000000000', // Mock iOS
    messagingSenderId: '441174887983',
    projectId: 'rbp-chanikarnn',
    storageBucket: 'rbp-chanikarnn.firebasestorage.app',
    iosBundleId: 'com.example.schoolLeaveApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfTTxNt5EXXPk0w15YlH-EH4c_0sFkLjo',
    appId: '1:441174887983:ios:0000000000000000000000',
    messagingSenderId: '441174887983',
    projectId: 'rbp-chanikarnn',
    storageBucket: 'rbp-chanikarnn.firebasestorage.app',
    iosBundleId: 'com.example.schoolLeaveApp.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfTTxNt5EXXPk0w15YlH-EH4c_0sFkLjo',
    appId: '1:441174887983:web:953d6e29407d3a0d3d00da',
    messagingSenderId: '441174887983',
    projectId: 'rbp-chanikarnn',
    authDomain: 'rbp-chanikarnn.firebaseapp.com',
    storageBucket: 'rbp-chanikarnn.firebasestorage.app',
    measurementId: 'G-902BBPMWC8',
  );
}
